apiVersion: v1
kind: Secret
metadata:
  name: {{ required "You must specify the application name" .Values.name }}-secret
  labels: 
    secret-sha: {{ required "You must specify the secret values" .Values.secret | toJson | sha1sum }}
{{ include "secret-labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
{{ include "secret-contents" . | nindent 2 }}    
